"""
satguard/processing/demo.py
Deterministic, explicitly synthetic demonstration data.

Purpose and limits
------------------
DEMO mode exists so the product can be explored without Sentinel credentials. It renders
synthetic rasters that are physically plausible and georeferenced to a real location, so
the whole pipeline can be exercised end to end.

These are **not satellite observations**. Every artefact produced here carries
`source="DEMO"` and `synthetic=True`, and each scene ships the ground-truth mask it was
built from so the detector's output can be checked against a known answer.

DEMO data is never a fallback for LIVE mode: if credentials are missing, LIVE must fail
loudly rather than quietly returning synthetic results.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from satguard.geospatial.area_of_interest import AOI, MonitoringMode, build_aoi
from satguard.geospatial.raster import GeoTransform
from satguard.processing.preprocess import build_quality_mask

logger = logging.getLogger("satguard.demo")

DEMO_SOURCE = "DEMO"

# Reflectance-like values for the surface classes used to build scenes. These are
# plausible Sentinel-2 L2A surface reflectance values by relative magnitude; they are
# synthetic and are not calibrated to any real acquisition.
_SURFACE_REFLECTANCE: Dict[str, Dict[str, float]] = {
    # dark, strongly absorbing in SWIR: open water
    "water":    {"B02": 280, "B03": 260, "B04": 240, "B06": 180, "B08": 110, "B11": 90,  "B12": 70},
    # moderate visible, high NIR: vegetation
    "vegetation": {"B02": 700, "B03": 900, "B04": 800, "B06": 2100, "B08": 3400, "B11": 2200, "B12": 1400},
    # bright visible and SWIR: bare rock and soil
    "bare":     {"B02": 1500, "B03": 1600, "B04": 1700, "B06": 2000, "B08": 1900, "B11": 2500, "B12": 2300},
    # high visible, low NIR/SWIR: built-up surfaces
    "built_up": {"B02": 1900, "B03": 2000, "B04": 2100, "B06": 2300, "B08": 2000, "B11": 2600, "B12": 2400},
    # very high visible, very low NIR/SWIR: snow and ice
    "snow":     {"B02": 2900, "B03": 3100, "B04": 3200, "B06": 1700, "B08": 900,  "B11": 500,  "B12": 300},
}

# Sentinel-2 Scene Classification Layer codes. Snow and ice is class 11; class 3 is
# cloud shadow, so labelling ice as 3 would discard the entire glacier as unusable.
_SCL_CLASS: Dict[str, int] = {
    "water": 6, "vegetation": 4, "bare": 5, "built_up": 5, "snow": 11,
}

BANDS: Tuple[str, ...] = ("B02", "B03", "B04", "B06", "B08", "B11", "B12")


class DemoError(Exception):
    error_code = "DEMO_GENERATION_FAILED"


@dataclass
class DemoScene:
    """One synthetic scene, with the truth that was used to build it."""
    captured: datetime
    bands: Dict[str, np.ndarray]
    scl: np.ndarray
    description: str
    synthetic: bool = True
    source: str = DEMO_SOURCE

    def quality_mask(self, monitoring_mode: Optional[str] = None) -> "Any":
        """
        Build the usable-data mask for this scene.

        The monitoring mode matters: SCL class 3 is snow and ice, which is unusable for
        most monitoring but is exactly the subject of glacier monitoring. Masking it
        unconditionally would leave a glacier comparison with no valid snow pixels.
        """
        mask = build_quality_mask(self.scl, self.scl.shape)
        return mask.reject_for_mode(monitoring_mode) if monitoring_mode else mask

    def to_dict(self) -> Dict[str, Any]:
        return {
            "captured": self.captured.isoformat(),
            "description": self.description,
            "synthetic": self.synthetic,
            "source": self.source,
            "shape": list(self.scl.shape),
        }


@dataclass
class DemoDataset:
    """
    A georeferenced pair of synthetic scenes plus the ground truth describing what
    actually changed between them.
    """
    name: str
    aoi: AOI
    transform: GeoTransform
    crs: str
    baseline: DemoScene
    current: DemoScene
    truth_mask: np.ndarray
    scenario: str
    notes: str = ""
    synthetic: bool = True
    source: str = DEMO_SOURCE

    @property
    def truth_area_m2(self) -> float:
        return float(np.count_nonzero(self.truth_mask) * _pixel_area(self.transform))

    def to_dict(self) -> Dict[str, Any]:
        """Manifest. Everything a reviewer needs to know this data is synthetic."""
        return {
            "name": self.name,
            "scenario": self.scenario,
            "source": self.source,
            "synthetic": self.synthetic,
            "disclaimer": (
                "Synthetic demonstration data generated by satguard.processing.demo. "
                "These are not satellite observations and must not be used for any "
                "operational, regulatory or safety decision."
            ),
            "aoi": self.aoi.to_dict(),
            "crs": self.crs,
            "grid": {
                "width": int(self.baseline.scl.shape[1]),
                "height": int(self.baseline.scl.shape[0]),
            },
            "baseline": self.baseline.to_dict(),
            "current": self.current.to_dict(),
            "truth": {
                "changed_pixels": int(np.count_nonzero(self.truth_mask)),
                "changed_area_m2": round(self.truth_area_m2, 2),
                "changed_area_km2": round(self.truth_area_m2 / 1e6, 6),
            },
            "notes": self.notes,
        }


def _pixel_area(transform: GeoTransform) -> float:
    """Square metres per pixel, using the raster's own centre latitude."""
    return transform.pixel_area_m2(transform.f + transform.e / 2.0)


# ----------------------------------------------------------------------
# Named demonstration sites, covering the regression scenarios.
# ----------------------------------------------------------------------


@dataclass
class DemoSite:
    name: str
    bounds: Tuple[float, float, float, float]
    monitoring_mode: MonitoringMode
    scenario: str
    description: str


DEMO_SITES: Tuple[DemoSite, ...] = (
    DemoSite(
        "tehri_dam_construction",
        (78.58, 30.28, 78.72, 30.40),
        MonitoringMode.INFRASTRUCTURE,
        "new_construction",
        "New built-up construction beside an existing dam and reservoir.",
    ),
    DemoSite(
        "south_lhonak_glacier",
        (79.05, 32.16, 79.20, 32.28),
        MonitoringMode.GLACIER,
        "glacier_retreat",
        "Snow and ice cover shrinking on a high-altitude glacier surface.",
    ),
    DemoSite(
        "siachen_glacier",
        (77.10, 35.20, 77.30, 35.36),
        MonitoringMode.GLACIER,
        "glacier_retreat",
        "Glacier margin retreat exposing bare ice-adjacent rock.",
    ),
    DemoSite(
        "sardar_sarovar_reservoir",
        (73.00, 24.30, 73.16, 24.44),
        MonitoringMode.WATER_BODY,
        "reservoir_expansion",
        "Open-water extent expanding behind a reservoir dam.",
    ),
    DemoSite(
        "mumbai_coastal_flood",
        (72.80, 18.94, 72.94, 19.06),
        MonitoringMode.FLOOD,
        "coastal_flooding",
        "Flood inundation across low-lying coastal land and urban surfaces.",
    ),
    DemoSite(
        "generic_arbitrary_aoi",
        (0.0, 0.0, 0.0, 0.0),
        MonitoringMode.GENERAL,
        "new_construction",
        "Anywhere on Earth: DEMO sites are generated from arbitrary bounds.",
    ),
)


def demo_site(name: str) -> DemoSite:
    for site in DEMO_SITES:
        if site.name == name:
            return site
    raise DemoError(
        f"Unknown DEMO site '{name}'. Available: {[s.name for s in DEMO_SITES]}"
    )


def available_demo_sites() -> List[Dict[str, Any]]:
    return [
        {
            "name": s.name,
            "monitoring_mode": s.monitoring_mode.value,
            "scenario": s.scenario,
            "description": s.description,
            "bounds": list(s.bounds) if any(s.bounds) else None,
        }
        for s in DEMO_SITES
    ]


# ----------------------------------------------------------------------
# Scenario rendering
# ----------------------------------------------------------------------


def _noise(rng: np.random.Generator, shape: Tuple[int, int], sigma: float = 0.02):
    return 1.0 + rng.normal(0.0, sigma, shape)


def _render(
    classes: np.ndarray,
    seed: int,
    shape: Tuple[int, int],
) -> Tuple[Dict[str, np.ndarray], np.ndarray]:
    """Render reflectance bands and an SCL grid from a surface-class map."""
    rng = np.random.default_rng(seed)
    bands: Dict[str, np.ndarray] = {}
    for band in BANDS:
        plane = np.zeros(shape, dtype=np.float64)
        for name, values in _SURFACE_REFLECTANCE.items():
            selected = classes == name
            if selected.any():
                plane[selected] = values[band]
        bands[band] = np.maximum(plane * _noise(rng, shape), 1.0)

    scl = np.zeros(shape, dtype=np.uint8)
    for name, code in _SCL_CLASS.items():
        scl[classes == name] = code
    return bands, scl


def _rect(shape: Tuple[int, int], row0: float, col0: float, height: float, width: float) -> np.ndarray:
    """Axis-aligned rectangle in fractional grid coordinates."""
    rows, cols = shape
    r0, r1 = int(row0 * rows), int((row0 + height) * rows)
    c0, c1 = int(col0 * cols), int((col0 + width) * cols)
    out = np.zeros(shape, dtype=bool)
    out[max(r0, 0):min(r1, rows), max(c0, 0):min(c1, cols)] = True
    return out


def _base_classes(
    scenario: str, shape: Tuple[int, int], rng: np.random.Generator
) -> np.ndarray:
    """The undisturbed surface present before the scenario's event."""
    classes = np.full(shape, "vegetation", dtype=object)

    if scenario in ("glacier_retreat",):
        classes[:] = "snow"
        classes[_rect(shape, 0.0, 0.0, 0.30, 1.0)] = "bare"
    elif scenario in ("reservoir_expansion", "coastal_flooding"):
        classes[:] = "bare"
        classes[_rect(shape, 0.55, 0.0, 0.45, 1.0)] = "water"
        classes[_rect(shape, 0.0, 0.70, 0.25, 0.30)] = "built_up"
    else:
        classes[_rect(shape, 0.60, 0.0, 0.40, 1.0)] = "water"
        classes[_rect(shape, 0.05, 0.05, 0.20, 0.20)] = "bare"
    return classes


def _apply_event(
    scenario: str, classes: np.ndarray, rng: np.random.Generator
) -> Tuple[np.ndarray, np.ndarray, str]:
    """
    Apply the scenario's event, returning the new class map, the ground-truth change
    mask, and a plain description of what was applied.
    """
    shape = classes.shape
    updated = classes.copy()
    truth = np.zeros(shape, dtype=bool)

    if scenario == "new_construction":
        patch = _rect(shape, 0.30, 0.30, 0.22, 0.22)
        updated[patch] = "built_up"
        truth |= patch
        description = "a new built-up construction site appeared"

    elif scenario == "glacier_retreat":
        # The margin becomes exposed bare ground: snow and ice lost, rock revealed.
        exposed = _rect(shape, 0.26, 0.0, 0.10, 1.0)
        updated[exposed] = "bare"
        truth |= exposed
        description = "the snow and ice margin retreated, exposing bare ground"

    elif scenario == "reservoir_expansion":
        flooded = _rect(shape, 0.40, 0.0, 0.18, 1.0)
        updated[flooded] = "water"
        truth |= flooded
        description = "open water expanded upstream"

    elif scenario == "coastal_flooding":
        inundated = _rect(shape, 0.45, 0.10, 0.25, 0.80)
        updated[inundated] = "water"
        truth |= inundated
        description = "flood water inundated low-lying land"

    else:
        raise DemoError(f"Unknown DEMO scenario '{scenario}'")

    return updated, truth, description


def build_demo_dataset(
    aoi: Optional[AOI] = None,
    bounds: Optional[Tuple[float, float, float, float]] = None,
    monitoring_mode: Optional[str] = None,
    scenario: str = "new_construction",
    baseline_date: Optional[datetime] = None,
    interval_days: int = 15,
    shape: Tuple[int, int] = (200, 200),
    crs: str = "EPSG:4326",
    seed: int = 20240610,
    name: Optional[str] = None,
) -> DemoDataset:
    """
    Build a labelled synthetic comparison for any AOI.

    The returned `truth_mask` records exactly which pixels were changed by the scenario,
    so detector output can be scored against ground truth instead of merely inspected.
    """
    if aoi is None:
        if bounds is None:
            raise DemoError("Provide either an AOI or explicit bounds for a DEMO dataset")
        mode = MonitoringMode(monitoring_mode or "general")
        aoi = build_aoi(bbox=list(bounds), monitoring_mode=mode)

    mode = MonitoringMode(monitoring_mode or aoi.monitoring_mode.value)
    if scenario not in _SUPPORTED_SCENARIOS:
        raise DemoError(
            f"Unknown DEMO scenario '{scenario}'. Supported: {sorted(_SUPPORTED_SCENARIOS)}"
        )

    bounds = tuple(aoi.geometry.bounds)
    width, height = shape
    transform = GeoTransform.from_bounds(bounds, width, height)

    # AOI geometry is honoured: pixels outside it are not part of the demonstration.
    inside = aoi.mask_for(transform, (height, width))

    rng = np.random.default_rng(seed)
    baseline_classes = _base_classes(scenario, shape, rng)
    current_classes, event_region, description = _apply_event(
        scenario, baseline_classes, rng
    )
    current_classes = np.where(inside, current_classes, baseline_classes)

    # Ground truth is the set of pixels whose surface actually changed, not the whole
    # event rectangle. Part of an event region may already have been the target surface,
    # and counting those pixels would understate the detector for no good reason.
    changed = baseline_classes != current_classes
    truth_mask = changed & inside & event_region

    baseline = datetime(2024, 6, 10, tzinfo=timezone.utc) if baseline_date is None else baseline_date
    if baseline.tzinfo is None:
        baseline = baseline.replace(tzinfo=timezone.utc)

    baseline_bands, baseline_scl = _render(baseline_classes, seed, shape)
    current_bands, current_scl = _render(current_classes, seed + 1, shape)

    # Outside the requested AOI the two scenes must be bit-identical. The AOI is what the
    # user asked to monitor, so nothing beyond it may vary between the pair; leaving the
    # independent noise field in place would show up as change the user never requested.
    for band in BANDS:
        current_bands[band][~inside] = baseline_bands[band][~inside]
    current_scl[~inside] = baseline_scl[~inside]

    baseline_scene = DemoScene(
        captured=baseline,
        bands=baseline_bands,
        scl=baseline_scl,
        description=f"Synthetic pre-event scene ({scenario}).",
    )
    current_scene = DemoScene(
        captured=baseline + timedelta(days=interval_days),
        bands=current_bands,
        scl=current_scl,
        description=f"Synthetic scene {interval_days} days later in which {description}.",
    )

    return DemoDataset(
        name=name or f"{aoi.id}_{scenario}",
        aoi=aoi,
        transform=transform,
        crs=crs,
        baseline=baseline_scene,
        current=current_scene,
        truth_mask=truth_mask,
        scenario=scenario,
        notes=(
            f"{description}. Ground truth: "
            f"{int(np.count_nonzero(truth_mask))} changed pixels."
        ),
    )


_SUPPORTED_SCENARIOS = {
    "new_construction", "glacier_retreat", "reservoir_expansion", "coastal_flooding",
}


def scenarios_for_mode(mode: str) -> List[str]:
    """Scenarios that make sense for a monitoring mode."""
    mapping = {
        MonitoringMode.GENERAL.value: ["new_construction", "coastal_flooding"],
        MonitoringMode.INFRASTRUCTURE.value: ["new_construction", "coastal_flooding"],
        MonitoringMode.GLACIER.value: ["glacier_retreat"],
        MonitoringMode.WATER_BODY.value: ["reservoir_expansion"],
        MonitoringMode.FLOOD.value: ["coastal_flooding"],
        MonitoringMode.VEGETATION.value: ["new_construction"],
    }
    return mapping.get(str(mode), ["new_construction"])