import React from 'react';
import { AnalystReport } from '../types/api';
import { FileText, Cpu, AlertTriangle, ShieldCheck } from 'lucide-react';

interface AnalystReportViewProps {
  report: AnalystReport | null | undefined;
  loading?: boolean;
}

export const AnalystReportView: React.FC<AnalystReportViewProps> = ({ report, loading }) => {
  if (loading) {
    return (
      <div className="gov-panel">
        <div className="gov-panel-body" style={{ display: 'flex', justifyContent: 'center', padding: '32px' }}>
          <div className="gov-spinner" />
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="gov-panel">
        <div className="gov-panel-header">
          <div className="gov-panel-title">Groq Evidence Analyst Synthesis</div>
        </div>
        <div className="gov-panel-body" style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '32px' }}>
          No Groq Evidence Analyst report generated for this location yet.
        </div>
      </div>
    );
  }

  const safeFormat = (val: any): string => {
    if (typeof val === 'string') return val;
    if (typeof val === 'number') return val.toString();
    if (val && typeof val === 'object') {
      return Object.entries(val)
        .map(([k, v]) => `${k}: ${typeof v === 'object' ? JSON.stringify(v) : v}`)
        .join(', ');
    }
    return String(val ?? '');
  };

  const contributing = (report.contributing_evidence || []).map(safeFormat);
  const uncertainties = (report.uncertainties || []).map(safeFormat);

  return (
    <div className="gov-panel" aria-label="Analyst Synthesis Report">
      <div className="gov-panel-header">
        <div className="gov-panel-title">
          <FileText size={16} color="var(--accent-cyan)" />
          <span>Groq Evidence Analyst Synthesis</span>
          <span style={{ fontSize: '11px', background: 'rgba(14, 165, 233, 0.15)', color: '#38BDF8', padding: '2px 8px', borderRadius: '4px', border: '1px solid rgba(14, 165, 233, 0.3)' }}>
            LLM ASSISTED
          </span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', fontSize: '11px', color: 'var(--text-muted)' }}>
          <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
            <Cpu size={13} />
            <span>MODEL: <strong style={{ color: 'var(--text-secondary)' }}>{report.model}</strong></span>
          </span>
          <span>PROMPT: {report.prompt_version || 'v5.0.0'}</span>
        </div>
      </div>

      <div className="gov-panel-body" style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        {/* Strict Advisory Warning */}
        <div style={{ background: 'rgba(239, 68, 68, 0.12)', borderLeft: '4px solid var(--risk-high)', padding: '10px 14px', borderRadius: '4px', fontSize: '12px' }}>
          <strong style={{ color: '#F87171' }}>OPERATIONAL BOUNDARY:</strong> This analyst synthesis is generated by{' '}
          <span style={{ color: '#FFF' }}>Groq Evidence Analyst ({report.model})</span> for contextual narrative support.{' '}
          <strong style={{ color: '#FFF' }}>It does NOT override or alter the authoritative Phase 4 deterministic risk score.</strong>
        </div>

        {/* Executive Summary */}
        <div style={{ background: 'var(--bg-card)', padding: '16px', borderRadius: '6px', border: '1px solid var(--border-default)' }}>
          <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '8px' }}>
            Executive Intelligence Summary
          </div>
          <p style={{ fontSize: '13px', color: 'var(--text-primary)', lineHeight: 1.6 }}>
            {report.executive_summary}
          </p>
        </div>

        {/* Evidence & Risk Interpretation */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
          <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '6px', border: '1px solid var(--border-default)' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '6px' }}>
              Evidence Interpretation
            </div>
            <p style={{ fontSize: '13px', color: 'var(--text-primary)', lineHeight: 1.5 }}>
              {report.evidence_interpretation}
            </p>
          </div>

          <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '6px', border: '1px solid var(--border-default)' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '6px' }}>
              Risk Context Interpretation
            </div>
            <p style={{ fontSize: '13px', color: 'var(--text-primary)', lineHeight: 1.5 }}>
              {report.risk_interpretation}
            </p>
          </div>
        </div>

        {/* Recommended Action */}
        <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '6px', border: '1px solid var(--border-default)' }}>
          <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--accent-cyan)', textTransform: 'uppercase', marginBottom: '6px' }}>
            Analyst Recommended Monitoring Action
          </div>
          <p style={{ fontSize: '13px', color: 'var(--text-primary)', lineHeight: 1.5 }}>
            {report.recommended_monitoring_action}
          </p>
        </div>

        {/* Lists: Contributing Evidence & Uncertainties */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
          <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '6px', border: '1px solid var(--border-default)' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '8px' }}>
              Key Supporting Evidence Elements
            </div>
            {contributing.length > 0 ? (
              <ul style={{ paddingLeft: '18px', fontSize: '12px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                {contributing.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            ) : (
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>None explicitly extracted</div>
            )}
          </div>

          <div style={{ background: 'var(--bg-card)', padding: '14px', borderRadius: '6px', border: '1px solid var(--border-default)' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: '#F59E0B', textTransform: 'uppercase', marginBottom: '8px' }}>
              Identified Analyst Uncertainties
            </div>
            {uncertainties.length > 0 ? (
              <ul style={{ paddingLeft: '18px', fontSize: '12px', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                {uncertainties.map((u, i) => (
                  <li key={i}>{u}</li>
                ))}
              </ul>
            ) : (
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>No major uncertainties noted</div>
            )}
          </div>
        </div>

        {/* Report Metadata Footer */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontSize: '11px', color: 'var(--text-muted)', borderTop: '1px solid var(--border-subtle)', paddingTop: '10px' }}>
          <span>Validation Status: <strong style={{ color: '#10B981' }}>{report.validation_status || 'VERIFIED'}</strong></span>
          <span>Generated: <span className="mono">{new Date(report.created_at).toLocaleString()}</span></span>
          <span>Report ID: <span className="mono">{report.id}</span></span>
        </div>
      </div>
    </div>
  );
};
